# Generated by Django 5.2.8 on 2026-09-30 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "tagline",
                    models.CharField(
                        help_text="Concise one-line summary displayed on project cards",
                        max_length=255,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("mechatronics", "Mechatronics & Robotics"),
                            ("software", "Software & Web Systems"),
                            ("embedded", "Embedded & IoT Systems"),
                            ("electronics", "Analogue & Digital Electronics"),
                            ("control", "Control Systems & Automation"),
                            ("research", "Research & Scientific Computing"),
                            ("experimental", "Hardware Experiments"),
                            ("university", "University Engineering Coursework"),
                            ("other", "Other Technology Project"),
                        ],
                        default="software",
                        max_length=30,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Card preview image (16:9 or 4:3 recommended)",
                        null=True,
                        upload_to="projects/thumbnails/",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Wide header visual or banner",
                        null=True,
                        upload_to="projects/hero/",
                    ),
                ),
                ("start_date", models.DateField(help_text="Project initiation date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Completion date (leave empty if ongoing or maintained)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept & Planning"),
                            ("in_development", "In Development"),
                            ("prototype", "Prototype Built"),
                            ("testing", "Testing & Verification"),
                            ("completed", "Completed"),
                            ("maintained", "Actively Maintained"),
                            ("archived", "Archived"),
                        ],
                        default="in_development",
                        max_length=30,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, prioritized in the homepage showcase",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Toggle public visibility"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, help_text="Repository URL (e.g. GitHub/GitLab)"
                    ),
                ),
                (
                    "live_url",
                    models.URLField(
                        blank=True,
                        help_text="Live web deployment or interactive demonstration",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        help_text="Technical manual, Sphinx/MkDocs, or datasheet",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube/Vimeo demonstration or prototype recording",
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        help_text="High-level engineering problem and system purpose"
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True,
                        help_text="Underlying technical difficulty or motivation",
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True,
                        help_text="Target performance, specs, or requirements",
                    ),
                ),
                (
                    "system_architecture",
                    models.TextField(
                        blank=True,
                        help_text="Hardware blocks, communication protocols (SPI, I2C, UART), or software diagrams",
                    ),
                ),
                (
                    "hardware_specs",
                    models.TextField(
                        blank=True,
                        help_text="Microcontrollers, sensors, operational amplifiers, actuators, power stages",
                    ),
                ),
                (
                    "software_stack_details",
                    models.TextField(
                        blank=True,
                        help_text="Firmware algorithms, Django architecture, API endpoints, or database structures",
                    ),
                ),
                (
                    "engineering_process",
                    models.TextField(
                        blank=True,
                        help_text="Iteration chronology: modeling -> circuit prototyping -> PCB -> firmware -> testing",
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True,
                        help_text="Unforeseen obstacles, noise issues, bugs, or physical limits",
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        help_text="Decisions made to achieve target performance",
                    ),
                ),
                (
                    "quantitative_results",
                    models.TextField(
                        blank=True,
                        help_text="Measured data, error bounds, frequency response, efficiency, or benchmarks",
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(
                        blank=True, help_text="Key takeaways and engineering insights"
                    ),
                ),
                (
                    "future_improvements",
                    models.TextField(
                        blank=True,
                        help_text="Next revisions, PCB spins, or feature additions",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Technologies, sensors, languages, or tools utilized",
                        related_name="projects",
                        to="core.technology",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["display_order", "-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. System Bill of Materials v1.2", max_length=200
                    ),
                ),
                ("file", models.FileField(upload_to="projects/files/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("bom", "Bill of Materials (BOM)"),
                            ("schematic", "Circuit Schematic / PCB"),
                            ("report", "Technical / Experimental Report"),
                            ("datasheet", "Datasheet / Component Spec"),
                            ("code", "Firmware / Source Archive"),
                            ("other", "Other Asset"),
                        ],
                        default="report",
                        max_length=30,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project File",
                "verbose_name_plural": "Project Files",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("photo", "Hardware Prototype / Rig"),
                            ("schematic", "Circuit Schematic"),
                            ("cad", "CAD / Mechanical Assembly"),
                            ("diagram", "System Block Diagram"),
                            ("screenshot", "Software Interface"),
                            ("plot", "Measurement / Oscilloscope Plot"),
                        ],
                        default="photo",
                        max_length=30,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. Sampling Rate, Operating Voltage, Latency, Bandwidth",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. 500 Hz, 3.3V / 5V DC, < 2.5 ms, 99.4%",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Context or measurement conditions",
                        max_length=255,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Metric",
                "verbose_name_plural": "Project Metrics",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
