# Generated by Django 5.2.8 on 2026-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Descriptive alternative text for screen readers",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("concept", "Concept"),
                    ("planning", "Planning"),
                    ("in_development", "In Development"),
                    ("prototype", "Prototype"),
                    ("testing", "Testing"),
                    ("completed", "Completed"),
                    ("maintained", "Maintained"),
                    ("archived", "Archived"),
                ],
                default="in_development",
                max_length=30,
            ),
        ),
    ]
