# Generated by Django 5.2.8 on 2026-09-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectimage_alt_text_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="next_milestone",
            field=models.CharField(
                blank=True,
                help_text="Next target milestone or deliverable (e.g. 'Fabricate PCB v2', 'Benchmark latency')",
                max_length=255,
            ),
        ),
    ]
