# Generated by Django 5.2.8 on 2026-09-30 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentlyBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief technical summary of current state"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="In Active Prototyping",
                        help_text="e.g. 'Fabricating test rig', 'Writing firmware', 'Drafting control loop'",
                        max_length=100,
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=50, help_text="Estimated progress percentage (0 - 100)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="Mechatronics & Embedded",
                        help_text="e.g. Embedded Systems, Django Web, Robotics",
                        max_length=100,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to repository or issue tracker",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currently Building Item",
                "verbose_name_plural": "Currently Building Items",
                "ordering": ["display_order", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(default="University in Italy", max_length=250),
                ),
                (
                    "degree",
                    models.CharField(
                        default="Bachelor of Science in Mechatronics Engineering / Engineering Science",
                        max_length=250,
                    ),
                ),
                ("location", models.CharField(default="Italy", max_length=150)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected graduation date or completion",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Context regarding specialization, methodology, and academic rigor",
                    ),
                ),
                (
                    "coursework",
                    models.TextField(
                        blank=True,
                        help_text="Key subjects (e.g. Analogue & Digital Electronics; Control Systems; Mechanics; Machine Design; Mathematics; Physics)",
                    ),
                ),
                (
                    "research_areas",
                    models.TextField(
                        blank=True,
                        help_text="Key academic and practical areas of interest",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Education Record",
                "verbose_name_plural": "Education Records",
                "ordering": ["display_order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "role",
                    models.CharField(
                        help_text="e.g. Founder, Technical Lead, Contributor",
                        max_length=150,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("period", models.CharField(default="2024 - Present", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Organization / Initiative",
                "verbose_name_plural": "Organizations & Initiatives",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        default="Ptah Kouekam Kamgou Luc Kevin",
                        help_text="Full legal/professional name",
                        max_length=200,
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        default="Engineer. Developer. Builder.",
                        help_text="Concise professional positioning (e.g. 'Engineer. Developer. Builder.')",
                        max_length=200,
                    ),
                ),
                (
                    "short_bio",
                    models.TextField(
                        default="Engineering student studying Mechatronics Engineering and Engineering Science in Italy. Building at the intersection of embedded electronics, mechanical systems, and robust software.",
                        help_text="Displayed in the hero section and SEO meta descriptions",
                    ),
                ),
                (
                    "long_bio",
                    models.TextField(
                        blank=True,
                        help_text="Detailed personal narrative used on the About page",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Italy",
                        help_text="General location (country/city)",
                        max_length=150,
                    ),
                ),
                (
                    "public_email",
                    models.EmailField(
                        blank=True,
                        help_text="Public contact email displayed if configured",
                        max_length=254,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Open to opportunities"),
                            ("collab", "Open to collaboration"),
                            ("research", "Focused on studies & research"),
                            ("busy", "Currently unavailable"),
                        ],
                        default="collab",
                        help_text="Current professional availability indicator",
                        max_length=30,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="High-resolution professional photo",
                        null=True,
                        upload_to="profile/",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Engineering workshop, CAD, or secondary hero visual",
                        null=True,
                        upload_to="profile/",
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(
                        blank=True,
                        help_text="Active CV/Resume document (PDF format recommended)",
                        null=True,
                        upload_to="resumes/",
                    ),
                ),
                (
                    "resume_version",
                    models.CharField(
                        blank=True,
                        default="2026.1",
                        help_text="Version identifier for the active CV",
                        max_length=50,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="Designed & engineered with precision using Django, HTMX, and Tailwind CSS.",
                        help_text="Brief technical or philosophical note in footer",
                        max_length=255,
                    ),
                ),
                (
                    "seo_meta_keywords",
                    models.CharField(
                        default="Mechatronics, Engineering, Embedded Systems, Django, Arduino, ESP32, Python, Electronics, Control Systems",
                        help_text="Comma-separated keywords for meta tags",
                        max_length=300,
                    ),
                ),
                (
                    "opengraph_image",
                    models.ImageField(
                        blank=True,
                        help_text="Social preview image (1200x630px recommended)",
                        null=True,
                        upload_to="seo/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("x", "X / Twitter"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("email", "Email"),
                            ("website", "Personal / Other Site"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("url", models.URLField(help_text="Complete URL with https://")),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="e.g. @username", max_length=100
                    ),
                ),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True,
                        help_text="Inline SVG path/markup for precise rendering",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_hero", models.BooleanField(default=True)),
                ("show_in_nav", models.BooleanField(default=False)),
                ("show_in_footer", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["display_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Technology Category",
                "verbose_name_plural": "Technology Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Degree, role, or milestone title", max_length=200
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        help_text="University, lab, company, or organization",
                        max_length=200,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently ongoing",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("experience", "Experience / Roles"),
                            ("milestone", "Milestone"),
                            ("achievement", "Achievement / Award"),
                            ("certification", "Certification"),
                            ("initiative", "Organization / Project"),
                        ],
                        default="experience",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Timeline Item",
                "verbose_name_plural": "Timeline Items",
                "ordering": ["-is_current", "-start_date", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True,
                        help_text="Inline SVG markup or SVG path for crisp rendering without third-party CDN fonts",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief note on how and where this technology is used",
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("learning", "Learning"),
                            ("working", "Working knowledge"),
                            ("comfortable", "Comfortable"),
                            ("strong", "Strong"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Optional proficiency assessment",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "years_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Optional years of active exposure",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, displayed in the homepage skills snapshot",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Official documentation or project URL"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.technologycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "ordering": ["category__display_order", "display_order", "name"],
            },
        ),
    ]
