# Generated by Django 5.2.8 on 2026-09-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_meta_description",
            field=models.TextField(
                blank=True,
                default="Personal engineering and software portfolio of Ptah Kouekam Kamgou Luc Kevin - Engineer. Developer. Builder.",
                help_text="Default SEO meta description for pages without custom descriptions",
            ),
        ),
    ]
