# Generated by Django 5.2.8 on 2026-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_sitesettings_default_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="availability_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Open to opportunities"),
                    ("collab", "Open to collaboration"),
                    ("research", "Focused on studies & research"),
                    ("busy", "Currently unavailable"),
                ],
                default="collab",
                help_text="Current professional availability indicator",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="location",
            field=models.CharField(
                blank=True,
                default="Italy",
                help_text="General location (country/city)",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="short_bio",
            field=models.TextField(
                blank=True,
                default="Engineering student studying Mechatronics Engineering and Engineering Science in Italy. Building at the intersection of embedded electronics, mechanical systems, and robust software.",
                help_text="Displayed in the hero section and SEO meta descriptions",
            ),
        ),
    ]
