# Generated by Django 5.2.8 on 2026-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_sitesettings_availability_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Featured links appear more prominently"
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="icon_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Standard icon name (e.g. github, linkedin, youtube, x, instagram, facebook, tiktok, website, other)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon_svg",
            field=models.TextField(
                blank=True,
                help_text="Optional inline SVG path/markup for custom rendering without arbitrary HTML",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("x", "X / Twitter"),
                    ("youtube", "YouTube"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("tiktok", "TikTok"),
                    ("website", "Personal Website"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
