# Generated by Django 5.2.8 on 2026-09-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_sociallink_featured_sociallink_icon_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentlybuilding",
            name="next_milestone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Next milestone or deliverable",
                max_length=255,
            ),
        ),
    ]
