# Generated by Django 5.2.8 on 2026-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_currentlybuilding_next_milestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Visible publicly across stack and showcase"
            ),
        ),
    ]
