# Generated by Django 5.2.8 on 2026-09-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_technology_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("education", "Education"),
                    ("work", "Work / Experience"),
                    ("project", "Project"),
                    ("milestone", "Milestone"),
                    ("organization", "Organization"),
                    ("certification", "Certification"),
                    ("achievement", "Achievement"),
                ],
                default="work",
                max_length=20,
            ),
        ),
    ]
