# Generated by Django 5.2.8 on 2026-09-30 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_timelineitem_item_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Curriculum Vitae", max_length=150)),
                (
                    "file",
                    models.FileField(
                        help_text="Upload CV document (PDF format required)",
                        upload_to="resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="e.g. 2025.1 or 1.0", max_length=20
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Designate as active resume. Activating this unsets any previous active resume.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume / CV",
                "verbose_name_plural": "Resumes / CVs",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
