# Generated by Django 5.2.8 on 2026-09-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_resume"),
        ("projects", "0003_project_next_milestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="associated_projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects created or maintained under this initiative",
                related_name="organizations",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
