# Generated by Django 5.2.8 on 2026-09-30 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Note Category",
                "verbose_name_plural": "Note Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Concise abstract or preview shown on note cards and SEO meta tags"
                    ),
                ),
                (
                    "content_markdown",
                    models.TextField(
                        help_text="Technical content written in GitHub-flavored Markdown"
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Compiled, sanitized HTML for safe and rapid rendering",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional banner or schematic diagram",
                        null=True,
                        upload_to="notes/covers/",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags (e.g. 'Control Systems, Arduino, Circuit Design')",
                        max_length=200,
                    ),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveIntegerField(
                        default=5, help_text="Estimated reading duration in minutes"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Toggle public availability"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Feature on homepage latest notes section",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Publication timestamp",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="notes.notecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engineering Note",
                "verbose_name_plural": "Engineering Notes",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
