# Generated by Django 5.2.8 on 2026-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="seo_description",
            field=models.CharField(
                blank=True,
                help_text="Custom meta description for search engines",
                max_length=255,
            ),
        ),
    ]
